version: '3.7'

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

volumes:
  elastic_data: {}
  #filebeat_data: {}
  
services:
  elasticsearch:
    <<: *base
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    ports: ['9200:9200']
    environment:
      discovery.type: single-node
    volumes: [ 'elastic_data:/usr/share/elasticsearch/data' ]

  kibana:
    <<: *base
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports: ['5601:5601']
    depends_on: ['elasticsearch']

  logstash:
    <<: *base
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    depends_on: ['elasticsearch']
    environment:
      CSV_DATA: ${CSV_DATA}
    # https://www.elastic.co/guide/en/logstash/current/docker-config.html
    volumes:
      #- ./logstash/:/tmp/logstash/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/data/csv/:${CSV_DATA}

  filebeat:
    <<: *base
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    depends_on: ['elasticsearch']
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS:-elasticsearch:9200}
      KIBANA_HOST: ${KIBANA_HOST:-kibana:5601}
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/logs/:/usr/share/filebeat/logs/:ro
  