version: "3.7"

#-----------------------------------------------------------------------
x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

x-pulsar-env: &pulsar-env
  PULSAR_HOST: pulsar
  PULSAR_TOPIC: conditions

x-python-base: &python-base
  <<: *base
  # https://pulsar.apache.org/docs/en/standalone-docker/#consume-a-message
  build:
    context: ./python
    #dockerfile: pulsar.Dockerfile
    args:
      #BASE_IMAGE: python:3.8.1-alpine3.11
      #BASE_IMAGE: apachepulsar/pulsar:2.4.2
      #BASE_IMAGE: python:3.8.1-slim-buster
      BASE_IMAGE: python:3.7.6-slim-buster
  environment:
    <<: *pulsar-env

x-java-base: &java-base
  <<: *base
  # https://pulsar.apache.org/docs/en/client-libraries/#java-client
  build:
    context: ./java
  environment:
    <<: *pulsar-env

#-----------------------------------------------------------------------
services:
  #-----------------------------------------------
  python-producer:
    <<: *python-base
    command: python3 producer.py

  python-consumer:
    <<: *python-base
    command: python3 consumer.py

  #----------------------
  java-producer:
    <<: *java-base
    environment:
      <<: *pulsar-env
      APP_MODE: producer

  java-consumer:
    <<: *java-base
    environment:
      <<: *pulsar-env
      APP_MODE: consumer
