services:
  pulsar:
    # Better to use k8s (local: mionikube, kind, ...)
    # cf.: https://pulsar.apache.org/docs/en/standalone-docker/#start-pulsar-in-docker
    # NOTE: use "pulsar" or "pulsar-all" for builtin connectors
    image: apachepulsar/pulsar-all:${PULSAR_VERSION}
    ports: ["6650:6650", "8080:8080"]
    volumes: ["pulsar_data:/pulsar/data"]
    command: bin/pulsar standalone

  pulsar-manager: # https://pulsar.apache.org/docs/en/administration-pulsar-manager/#set-administrator-account-and-password
    image: apachepulsar/pulsar-manager:v0.4.0
    ports: ["9527:9527", "7750:7750"] # https://stackoverflow.com/a/71052130/2592915
    environment:
      USERNAME: pulsar
      PASSWORD: pulsar
      PULSAR_CLUSTER: pulsar
      DRIVER_CLASS_NAME: org.postgresql.Driver
      LOG_LEVEL: DEBUG
      REDIRECT_HOST: http://127.0.0.1
      REDIRECT_PORT: 9527
      URL: jdbc:postgresql://127.0.0.1:5432/pulsar_manager
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    volumes: ["pulsar_manager_data:/pulsar-manager/pulsar-manager/dbdata"]

  pulsar-manager-set-super-user:
    # HACK for https://github.com/apache/pulsar-helm-chart/issues/108#issuecomment-1046001952
    image: radial/busyboxplus:curl
    environment:
      URL: http://pulsar-manager:7750
      USERNAME: pulsar
      PASSWORD: pulsar
    volumes: ["./pulsar-manager/:/dev/config"]
    command: /dev/config/set-super-user.sh
    depends_on: ["pulsar-manager"]

  elasticsearch:
    # https://pulsar.apache.org/docs/3.2.x/io-elasticsearch-sink/#configuration
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      discovery.type: single-node
    ports: ["9200:9200", "9300:9300"]
    volumes: ["elastic_data:/usr/share/elasticsearch/data"]
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports: ["5601:5601"]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on: ["elasticsearch"]

#-----------------------------------------------------------------------
volumes:
  pulsar_data: {}
  pulsar_manager_data: {}
  elastic_data: {}
